language: c
sudo: false
cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/tools
    - $HOME/buildtools
before_cache:
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
before_install: source travis/setup.sh
install:
 - pkg-config --list-all
 # Install reflex-host (not yet on hackage)
 - git clone https://github.com/bennofs/reflex-host
 - env SOURCE_PACKAGES="reflex-host/" travis/install.sh
script: travis/script.sh
matrix:
  include:
    - env: GHCVER=7.8.4 CABALVER=1.18
      compiler: ": #GHC 7.8.4"
      addons:
        apt:
          packages:
            - cabal-install-1.18
            - ghc-7.8.4
            - alex-3.1.4
            - happy-1.19.5
            - qt5-default
            - libqt5qml5
            - libqt5quick5
            - pkg-config
          sources: [hvr-ghc, ubuntu-sdk-team]
    - env: GHCVER=7.10.2 CABALVER=1.22 ROOT=1 ALLOW_NEWER="tagged,filepath"
      compiler: ": #GHC 7.10.2"
      addons:
        apt:
          packages:
            - cabal-install-1.22
            - ghc-7.10.2
            - alex-3.1.4
            - happy-1.19.5
            - qt5-default
            - libqt5qml5
            - libqt5quick5
            - pkg-config
          sources: [hvr-ghc, ubuntu-sdk-team]
    - env: GHCVER=head CABALVER=head ALLOW_NEWER="template-haskell,tagged"
      compiler: ": #GHC head"
      addons:
        apt:
          packages:
            - cabal-install-head
            - ghc-head
            - alex-3.1.4
            - happy-1.19.5
            - qt5-default
            - libqt5qml5
            - libqt5quick5
            - pkg-config
          sources: [hvr-ghc, ubuntu-sdk-team]
  allow_failures:
    - compiler: ": #GHC head"
  fast_finish: true
