sudo: false
cache:
  directories:
    - $HOME/hlint
before_install:
 - travis_retry cabal-$CABALVER update
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/happy/1.19.5/bin:/opt/alex/3.1.4/bin:$PATH
install:
 - cabal-$CABALVER sandbox init
 - git clone -b develop https://github.com/ryantrinkle/reflex reflex
 - git clone https://github.com/bennofs/reflex-host reflex-host
 - cabal-$CABALVER sandbox add-source $PWD/reflex
 - cabal-$CABALVER sandbox add-source $PWD/reflex-host
 - cabal-$CABALVER install --only-dependencies --enable-tests --enable-benchmarks -j

script:
 - travis/script.sh
 - hlint src

matrix:
  allow_failures:
   - env: CABALVER=head GHCVER=head 
  include:
    - env: CABALVER=1.18 GHCVER=7.8.4
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.8.4, alex-3.1.4, happy-1.19.5, hlint], sources: [hvr-ghc]}}
    - env: CABALVER=1.22 GHCVER=7.10.1
      addons: {apt: {packages: [cabal-install-1.22, ghc-7.10.1, alex-3.1.4, happy-1.19.5, hlint],sources: [hvr-ghc]}}
    - env: CABALVER=head GHCVER=head
      addons: {apt: {packages: [cabal-install-head, ghc-head, alex-3.1.4, happy-1.19.5, hlint],  sources: [hvr-ghc]}}
  fast_finish: true
